# Generated by Django 3.0.2 on 2020-09-27 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0008_auto_20200802_1120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_app', '0003_auto_20200705_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_transfer',
            name='shift_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers', to='structure_app.Shift_work'),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='fr_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_fr_budget', to='financial_app.Budget'),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='fr_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_fr_investment', to='financial_app.Investment'),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='fr_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_fr_loan', to='financial_app.Loan'),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='fr_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_fr_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='fr_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_fr_wallet', to='financial_app.Wallet'),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='to_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_to_budget', to='financial_app.Budget'),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='to_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_to_investment', to='financial_app.Investment'),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='to_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_to_loan', to='financial_app.Loan'),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='money_transfer',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moneytransfers_to_wallet', to='financial_app.Wallet'),
        ),
    ]
