# Generated by Django 3.1.4 on 2021-07-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0004_auto_20200927_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_pos',
            field=models.BooleanField(default=0),
        ),
    ]
