# Generated by Django 3.1.4 on 2021-07-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0005_wallet_is_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_machines', to='financial_app.wallet'),
        ),
    ]
