# Generated by Django 4.1.6 on 2023-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "financial_app",
            "0007_alter_budget_budget_type_alter_budget_coordinator_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="is_enabled",
            field=models.BooleanField(default=1),
        ),
    ]
