# Generated by Django 4.2.7 on 2026-01-11 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_app', '0008_wallet_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_coordinator', to=settings.AUTH_USER_MODEL),
        ),
    ]
