# Generated by Django 4.2.7 on 2026-01-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0009_alter_budget_coordinator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Төсөв', 'verbose_name_plural': 'Төсөвүүд'},
        ),
        migrations.AddField(
            model_name='budget',
            name='returned',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('Төсөвлөсөн', 'Төсөвлөсөн'), ('Мөнгөө хүлээн авсан', 'Мөнгөө хүлээн авсан'), ('Барааг авч дууссан', 'Барааг авч дууссан'), ('Тооцоо тулгасан', 'Тооцоо тулгасан'), ('Дууссан', 'Дууссан')], default='Төсөвлөсөн', max_length=255, verbose_name='Төсвийн төлөв'),
        ),
    ]
