# Generated by Django 4.2.7 on 2026-01-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0010_alter_budget_options_budget_returned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget_type',
            options={'verbose_name': 'Төсвийн төрөл', 'verbose_name_plural': 'Төсвийн төрлүүд'},
        ),
        migrations.AddField(
            model_name='budget',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='oppressed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
