# Generated by Django 3.0.2 on 2020-08-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0002_auto_20200621_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='structure_app.Division'),
        ),
    ]
