# Generated by Django 3.0.2 on 2020-08-02 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0004_auto_20200802_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='free',
        ),
        migrations.AlterField(
            model_name='client',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='structure_app.Division'),
        ),
    ]
