# Generated by Django 3.0.2 on 2020-08-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0005_auto_20200802_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clean',
            new_name='free',
        ),
    ]
