# Generated by Django 3.0.2 on 2020-08-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0006_auto_20200802_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='room_clean',
            field=models.BooleanField(default=1),
        ),
    ]
