# Generated by Django 3.2.3 on 2021-05-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0008_auto_20200802_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='room_clean',
            new_name='clean',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='room_free',
            new_name='free',
        ),
    ]
