# Generated by Django 3.1.4 on 2021-05-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0009_auto_20210529_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='erembe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
