# Generated by Django 3.1.4 on 2021-06-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0010_division_erembe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
