# Generated by Django 3.1.4 on 2021-06-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0011_auto_20210629_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.IntegerField(),
        ),
    ]
