# Generated by Django 3.2.3 on 2022-11-07 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0012_auto_20210629_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_value',
            name='kitchen_bill_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
