# Generated by Django 3.2.12 on 2023-02-07 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0013_configuration_value_kitchen_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_value',
            name='district_code',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)]),
        ),
    ]
