# Generated by Django 3.2.12 on 2023-02-07 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0015_alter_configuration_value_district_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_value',
            name='bill_id_suffix',
            field=models.BigIntegerField(blank=True, default=100000, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='configuration_value',
            name='district_code',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)]),
        ),
    ]
