# Generated by Django 3.2 on 2023-02-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0016_auto_20230207_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
