# Generated by Django 4.1.6 on 2023-02-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0017_alter_client_created_by_alter_customer_created_by_and_more'),
        ('structure_app', '0017_alter_customer_mobile'),
    ]

    operations = [
    ]
