# Generated by Django 4.1.6 on 2023-02-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0018_error_list'),
        ('structure_app', '0018_merge_20230216_2128'),
    ]

    operations = [
    ]
