# Generated by Django 4.1.6 on 2023-02-17 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure_app', '0019_merge_0018_error_list_0018_merge_20230216_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_list',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL),
        ),
    ]
