# Generated by Django 4.1.6 on 2023-03-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0020_alter_error_list_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='client',
            name='free',
        ),
        migrations.RemoveField(
            model_name='client',
            name='minibarFull',
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='structure_app.division'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
