# Generated by Django 4.1.6 on 2023-03-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0021_remove_client_clean_remove_client_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error_list',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='error_list',
            name='created_by',
        ),
    ]
