# Generated by Django 3.2 on 2023-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0022_remove_error_list_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Printer name', max_length=255)),
                ('ip', models.CharField(default='192.168.1.9', max_length=255)),
                ('port', models.IntegerField(default=9100, max_length=255)),
            ],
        ),
    ]
