# Generated by Django 3.2 on 2023-03-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0023_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='port',
            field=models.IntegerField(default=9100),
        ),
    ]
