# Generated by Django 4.1.6 on 2023-03-19 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("structure_app", "0024_alter_printer_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="error_list",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="error_list",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(class)s_createdby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
