# Generated by Django 4.2.7 on 2025-02-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structure_app", "0026_shift_work_finished_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_clean",
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name="client",
            name="is_free",
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name="client",
            name="minibarFull",
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
