# Generated by Django 4.2.7 on 2025-02-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "structure_app",
            "0027_client_is_clean_client_is_free_client_minibarfull_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
    ]
