# Generated by Django 4.2.7 on 2025-02-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structure_app", "0028_remove_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
