# Generated by Django 4.2.7 on 2026-01-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0029_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_clean',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='client',
            name='minibarFull',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
