# Generated by Django 3.0.2 on 2020-08-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='commodity-images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-images'),
        ),
    ]
