# Generated by Django 3.0.2 on 2020-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20200801_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='is_created',
            field=models.BooleanField(default=0),
        ),
    ]
