# Generated by Django 3.2.3 on 2021-05-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
