# Generated by Django 3.1.4 on 2021-06-26 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_product_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gramm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fraction',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='whole_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraction_items', to='product_app.product'),
        ),
    ]
