# Generated by Django 3.1.4 on 2021-07-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_product_whole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='whole',
        ),
    ]
