# Generated by Django 3.1.4 on 2021-07-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_remove_product_whole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='whole_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraction_items', to='product_app.product'),
        ),
    ]
