# Generated by Django 3.1.4 on 2021-07-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_auto_20210703_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_fraction',
            new_name='is_ingrediented',
        ),
        migrations.RemoveField(
            model_name='product',
            name='whole_item',
        ),
    ]
