# Generated by Django 3.1.4 on 2021-07-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_auto_20210703_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='unit_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
