# Generated by Django 3.1.4 on 2021-07-24 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0012_auto_20210705_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': 'Бүтээгдэхүүн материалын орц'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='product_app.commodity', verbose_name='Бүтээгдэхүүнд орох материал'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='product_app.product', verbose_name='Бүтээгдэхүүн'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Ingredient_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('size', models.PositiveIntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_commoditied', to='product_app.product', verbose_name='Бүтээгдэхүүнд орох бүтээгдэхүүн')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_product_createdby', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_producted', to='product_app.product', verbose_name='Бүтээгдэхүүн')),
                ('size_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_products', to='product_app.size_type')),
            ],
            options={
                'verbose_name_plural': 'Бүтээгдэхүүн бүтээгдэхүүний орц',
            },
        ),
    ]
