# Generated by Django 3.2.3 on 2022-11-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0014_remove_ingredient_product_size_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='print_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
