# Generated by Django 3.2 on 2023-02-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_product_print_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='print_name',
        ),
    ]
