# Generated by Django 3.2 on 2023-02-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0016_remove_product_print_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_product',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_commoditied', to='product_app.product', verbose_name='Бүтээгдэхүүнд орох орц бүтээгдэхүүн'),
        ),
    ]
