# Generated by Django 3.2 on 2023-02-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_alter_ingredient_product_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='same_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='same_commodity', to='product_app.product'),
        ),
    ]
