# Generated by Django 4.1.6 on 2023-02-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_alter_basic_asset_created_by_and_more'),
        ('product_app', '0017_alter_ingredient_product_commodity'),
    ]

    operations = [
    ]
