# Generated by Django 3.2 on 2023-02-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_commodity_same_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_single_ingrediented',
            field=models.BooleanField(default=0, verbose_name='Ганц орцтой бүтээгдэхүүн мөн үү? Жишээ: 50гр архи, 250 гр жүүс, 100гр дарс ...'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_ingrediented',
            field=models.BooleanField(default=0, verbose_name='Орцтой бүтээгдэхүүн мөн үү? Жишээ: граммын архи, жүүс, дарс, cocktail, хоол ...'),
        ),
    ]
