# Generated by Django 3.2 on 2023-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0019_auto_20230217_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='unit_size',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_ingrediented',
            field=models.BooleanField(default=0, verbose_name='Орцтой бүтээгдэхүүн?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_single_ingrediented',
            field=models.BooleanField(default=0, verbose_name='Ганц орцтой бүтээгдэхүүн?'),
        ),
    ]
