# Generated by Django 3.2 on 2023-02-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0020_auto_20230217_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='size',
        ),
    ]
