# Generated by Django 3.2 on 2023-02-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0021_remove_commodity_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='same_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_single_ingrediented',
        ),
        migrations.AddField(
            model_name='product',
            name='same_commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='same_product', to='product_app.commodity'),
        ),
    ]
