# Generated by Django 3.2 on 2023-02-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0022_auto_20230217_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='unit_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
