# Generated by Django 3.2 on 2023-02-27 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0023_commodity_unit_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Хэдэн граммын бүтээгдэхүүн вэ?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gramm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Граммын бүтээгдэхүүн үү?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='same_commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='same_products', to='product_app.commodity', verbose_name='Материалруу хөр'),
        ),
    ]
