# Generated by Django 3.2 on 2023-02-27 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0025_auto_20230227_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_balance',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='product_app.commodity'),
        ),
        migrations.AlterField(
            model_name='item_balance_log',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_balance_logs', to='product_app.commodity'),
        ),
        migrations.AlterField(
            model_name='item_transfer',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='product_app.commodity'),
        ),
    ]
