# Generated by Django 3.2 on 2023-02-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0026_auto_20230227_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gramm',
            field=models.BooleanField(default=0, verbose_name='Граммын бүтээгдэхүүн?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gramm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Грамм?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='same_commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='same_products', to='product_app.commodity', verbose_name='Адил материал?'),
        ),
    ]
