# Generated by Django 4.1.6 on 2023-02-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_merge_20230216_2127'),
        ('product_app', '0026_auto_20230227_1032'),
    ]

    operations = [
    ]
