# Generated by Django 4.1.6 on 2023-02-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0027_auto_20230227_1708'),
        ('product_app', '0027_merge_20230227_1237'),
    ]

    operations = [
    ]
