# Generated by Django 4.2.7 on 2026-01-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0030_remove_client_is_clean_remove_client_is_free_and_more'),
        ('product_app', '0028_merge_20230227_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity_category',
            name='Division',
        ),
        migrations.AddField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Идэвхтэй юу?'),
        ),
        migrations.AlterField(
            model_name='broken_item',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient_product',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item_balance',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item_balance',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item_balance_log',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_transfer',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commodity_category',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commodity_categories', to='structure_app.division'),
        ),
    ]
