# Generated by Django 4.2.7 on 2026-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0029_remove_commodity_category_division_product_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='noat_payer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='register',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='ttd',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
