# Generated by Django 3.0.2 on 2020-09-23 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20200801_1153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_app', '0005_payment_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='payments',
            field=models.ManyToManyField(related_name='orders', through='payment_app.Order_payments', to='payment_app.Payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='payment_app.Order_detial', to='product_app.Product'),
        ),
    ]
