# Generated by Django 3.1.4 on 2021-07-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0006_auto_20200923_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detial',
            name='finished',
            field=models.BooleanField(default=0),
        ),
    ]
