# Generated by Django 3.1.4 on 2021-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0007_order_detial_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detial',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
