# Generated by Django 3.1.4 on 2021-07-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0008_order_detial_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
