# Generated by Django 3.1.4 on 2021-07-25 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_app', '0009_auto_20210725_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_discount_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
