# Generated by Django 3.1.4 on 2021-08-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0010_order_discount_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detial',
            name='temp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
