# Generated by Django 3.1.4 on 2021-08-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0011_order_detial_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detial',
            name='temp',
        ),
    ]
