# Generated by Django 3.1.4 on 2021-08-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0013_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
