# Generated by Django 3.2.12 on 2023-02-07 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure_app', '0013_configuration_value_kitchen_bill_number'),
        ('payment_app', '0014_remove_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bills',
        ),
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='payment_app.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='structure_app.client'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='structure_app.customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='structure_app.division'),
        ),
        migrations.DeleteModel(
            name='Payment_bills',
        ),
    ]
