# Generated by Django 3.2.12 on 2023-02-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0015_auto_20230207_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='company_name',
            new_name='bill_id',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='discounted_amount',
            new_name='cash_amount',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='total_amount',
            new_name='city_tax',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='company_register',
            new_name='lottery',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='status',
            new_name='lottery_warning_msg',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='did_splited',
            new_name='success',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='got_ebarimt',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_id_suffix',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.IntegerField(choices=[(1, 'Байгууллагаас хувь иргэнд борлуулсан бараа, ажил үйлчилгээний баримт'), (3, 'Байгууллагаас байгууллагын хооронд борлуулсан бараа, ажил үйлчилгээний баримт'), (5, 'Нэхэмжлэхээр борлуулсан бараа, ажил, үйлчилгээний баримт')], null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_no',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='district_code',
            field=models.DecimalField(decimal_places=0, default=20, max_digits=2),
        ),
        migrations.AddField(
            model_name='bill',
            name='error_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='internal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='max_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='non_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='bill',
            name='pos_no',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bill',
            name='qr_data',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='register_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='return_bill_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=33, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_type',
            field=models.IntegerField(choices=[(1, 'НӨАТ тооцох баримт'), (2, 'НӨАТ-аас чөлөөлөгдөх бараа, ажил, үйлчилгээ борлуулсан баримт'), (3, 'НӨАТ 0% тооцох бараа, ажил, үйлчилгээ борлуулсан баримт')], null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
