# Generated by Django 3.2.12 on 2023-02-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0018_auto_20230207_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('1', 'Хувь хүн'), ('3', 'Байгууллага'), ('5', 'Нэхэмжлэл')], max_length=1, null=True),
        ),
    ]
