# Generated by Django 3.2.12 on 2023-02-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0019_alter_bill_bill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='success',
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Амжилттай илгээгдсэн'), ('2', 'Алдаа гарсан'), ('3', 'Буцаахаар хүсэлт гаргасан'), ('4', 'Амжилттай буцаагдсан'), ('5', 'Дахин илгээгдсэн'), ('6', 'Татварлуу илгээгдсэн')], max_length=1, null=True),
        ),
    ]
