# Generated by Django 3.2.12 on 2023-02-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0020_auto_20230208_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Бэлтгэгдэж байгаа'), ('1', 'Амжилттай илгээгдсэн'), ('2', 'Алдаа гарсан'), ('3', 'Буцаахаар хүсэлт гаргасан'), ('4', 'Амжилттай буцаагдсан'), ('5', 'Дахин илгээгдсэн'), ('6', 'Татварлуу илгээгдсэн')], max_length=1, null=True),
        ),
    ]
