# Generated by Django 3.2 on 2023-02-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0022_bill_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
