# Generated by Django 3.2 on 2023-02-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0023_bill_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='qr_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
