# Generated by Django 4.1.6 on 2023-02-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0024_alter_bill_created_by_alter_bill_qr_data_and_more'),
        ('payment_app', '0024_alter_bill_qr_data'),
    ]

    operations = [
    ]
